default:
    @just --list --unsorted

clean:
    cargo clean

check:
    cargo deny check
    cargo check --target xtensa-esp32s3-espidf
    cargo clippy --target xtensa-esp32s3-espidf

build:
    ESP_IDF_SDKCONFIG_DEFAULTS="${DEVBOX_WD}/firmware/ariadna/sdkconfig.defaults" cargo build --target xtensa-esp32s3-espidf

test:
    cargo test
