default:
    @just --list --unsorted

clean:
    cargo clean

check:
    cargo deny check
    cargo check --target wasm32-unknown-unknown
    cargo clippy --target wasm32-unknown-unknown

build:
    cargo build --release --target wasm32-unknown-unknown

test *ARGS:
    cargo test {{ARGS}}
